name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
        
  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nativeshell
      - name: Display structure of downloaded files
        run: ls -R
      - name: Prepare release artifact
        run: |
          zip -r --junk-paths nativeshell.zip ./*
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: NT Native Executable and install files
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/nativeshell.zip
          asset_name: nativeshell-${GITHUB_REF##*/}.i386.zip
          asset_content_type: application/zip

    
