name: Release

on:
  push:
    tags:
    - 'w*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Print Tag 2
        run: |
          git fetch --tags --force
          latest_tag=$(git describe --tags --abbrev=0)
          